# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "brodock-visage-app"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lindsay Holmwood", "Gabriel Mazetto"]
  s.date = "2012-03-22"
  s.description = "Visage is a web interface for viewing collectd statistics. It also provides a JSON interface onto collectd's RRD data, giving you an easy way to mash up the data."
  s.email = "brodock@gmail.com"
  s.executables = ["visage-app"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "AUTHORS",
    "Gemfile",
    "Gemfile.lock",
    "LICENCE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/visage-app",
    "features/builder.feature",
    "features/cli.feature",
    "features/data/config/with_no_profiles/.stub",
    "features/json.feature",
    "features/meta.feature",
    "features/profiles.feature",
    "features/step_definitions/form_steps.rb",
    "features/step_definitions/json_steps.rb",
    "features/step_definitions/result_steps.rb",
    "features/step_definitions/site_steps.rb",
    "features/step_definitions/visage_steps.rb",
    "features/step_definitions/webrat_steps.rb",
    "features/support/env.rb",
    "lib/visage-app.rb",
    "lib/visage-app/collectd/json.rb",
    "lib/visage-app/collectd/rrds.rb",
    "lib/visage-app/config.rb",
    "lib/visage-app/config.ru",
    "lib/visage-app/config/file.rb",
    "lib/visage-app/graph.rb",
    "lib/visage-app/helpers.rb",
    "lib/visage-app/patches.rb",
    "lib/visage-app/profile.rb",
    "lib/visage-app/public/favicon.gif",
    "lib/visage-app/public/images/active.png",
    "lib/visage-app/public/images/add.png",
    "lib/visage-app/public/images/caution.png",
    "lib/visage-app/public/images/hosts.png",
    "lib/visage-app/public/images/loader.gif",
    "lib/visage-app/public/images/metrics.png",
    "lib/visage-app/public/images/ok.png",
    "lib/visage-app/public/images/questions.png",
    "lib/visage-app/public/images/search.png",
    "lib/visage-app/public/javascripts/builder.js",
    "lib/visage-app/public/javascripts/graph.js",
    "lib/visage-app/public/javascripts/highcharts.js",
    "lib/visage-app/public/javascripts/highcharts.src.js",
    "lib/visage-app/public/javascripts/keyboard.js",
    "lib/visage-app/public/javascripts/message.js",
    "lib/visage-app/public/javascripts/mootools-1.2.3-core.js",
    "lib/visage-app/public/javascripts/mootools-1.2.5.1-more.js",
    "lib/visage-app/public/javascripts/mootools-core-1.4.0-full-compat.js",
    "lib/visage-app/public/javascripts/mootools-more-1.4.0.1.js",
    "lib/visage-app/public/stylesheets/message.css",
    "lib/visage-app/public/stylesheets/screen.css",
    "lib/visage-app/types.rb",
    "lib/visage-app/views/builder.haml",
    "lib/visage-app/views/builder_form.haml",
    "lib/visage-app/views/layout.haml",
    "lib/visage-app/views/profile.haml",
    "lib/visage-app/views/profiles.haml",
    "man/visage-app.5",
    "man/visage-app.5.ronn",
    "visage-app.gemspec"
  ]
  s.homepage = "http://visage-app.com/"
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.3")
  s.rubygems_version = "1.8.11"
  s.summary = "a web (interface | service) for viewing collectd statistics"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<tilt>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<errand>, ["= 0.7.3"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_development_dependency(%q<shotgun>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<webrat>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, ["~> 1.3.2"])
      s.add_runtime_dependency(%q<tilt>, ["~> 1.3"])
      s.add_runtime_dependency(%q<haml>, ["~> 3.1.4"])
      s.add_runtime_dependency(%q<errand>, ["= 0.7.3"])
      s.add_runtime_dependency(%q<yajl-ruby>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<librrd>, ["~> 1.0.2"])
    else
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<tilt>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<errand>, ["= 0.7.3"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<shotgun>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<webrat>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sinatra>, ["~> 1.3.2"])
      s.add_dependency(%q<tilt>, ["~> 1.3"])
      s.add_dependency(%q<haml>, ["~> 3.1.4"])
      s.add_dependency(%q<errand>, ["= 0.7.3"])
      s.add_dependency(%q<yajl-ruby>, ["~> 1.1.0"])
      s.add_dependency(%q<librrd>, ["~> 1.0.2"])
    end
  else
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<tilt>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<errand>, ["= 0.7.3"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<shotgun>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<webrat>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sinatra>, ["~> 1.3.2"])
    s.add_dependency(%q<tilt>, ["~> 1.3"])
    s.add_dependency(%q<haml>, ["~> 3.1.4"])
    s.add_dependency(%q<errand>, ["= 0.7.3"])
    s.add_dependency(%q<yajl-ruby>, ["~> 1.1.0"])
    s.add_dependency(%q<librrd>, ["~> 1.0.2"])
  end
end

